config/routes.rb
SampleApp::Application.routes.draw do
  get "adverts/adnew"
  get "adverts/choose"
  get "adverts/play"
  get "adverts/win"

  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'

  match '/adnew',   :to => 'adverts#adnew'
  match '/choose',  :to => 'adverts#choose'
  match '/play',    :to => 'adverts#play'
  match '/win',     :to => 'adverts#win'

  root :to => 'pages#home'

end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  def adnew
  end

  def choose
  end

  def play
  end

  def win
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign up"
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logo
		 image_tag("logo_gift_s.png", :alt => "SeeNWin", :class => "round")
	end

	# Return a title on a per-page basis
	def title
		base_title = "Ruby on Rails Tutorial Sample App"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adverts/adnew.html.erb
<h1>Adverts#adnew</h1>
<p>Find me in app/views/adverts/adnew.html.erb</p>

app/views/adverts/choose.html.erb
<h1>Adverts#choose</h1>
<p>Find me in app/views/adverts/choose.html.erb</p>
<% choose_btn = image_tag("choose2.png", :alt => "Choose", :class => "in_center  round") %>
<%= link_to choose_btn, play_path %>

app/views/adverts/play.html.erb
<h1>Adverts#play</h1>
<p>Find me in app/views/adverts/play.html.erb</p>
<% view_btn = image_tag("view1.png", :alt => "View", :class => "in_center  round") %>
<%= link_to view_btn, win_path %>
<p><%= link_to "Oops, I Win!", win_path, :class => "adverts_btn round" %></p>

app/views/adverts/win.html.erb
<h1>Adverts#win</h1>
<p>Find me in app/views/adverts/win.html.erb</p>
<%= image_tag("win.png", :alt => "Winner", :class => "in_center  round") %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
<!--      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
      <li><a href="http://russian.railstutorial.org/">Rails Tutorial in Russian</a></li>
 -->
 	  <li><%= link_to "for Buisness", adnew_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Sign in", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
  </head>
  <body>
  	<div class="container">
		<%= render 'layouts/header' %>
  		<section class="round">
    		<%= yield %>
    	</section>
      	<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h1>Hello to SeeNWin application</h1>
<p>
	This system is implementation of a Lottery game for real products in exchange for watching advertisements.
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<p> </p>
<%= link_to "Try your Luck", choose_path, :class => "try_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>